#!/bin/bash
sudo cat /etc/passwd | awk -F  ":" '{print $1 "   " $3 "   " $6}' | column -t
# echo ' all the information is found in this text file(cat /etc/passwd). we can use awk to print the columns that we want, -F allows you to specify a space seperator'
