#!/bin/bash
echo "Enter username you would like to delete?"
read username

not_found=`tput setaf 6`
found=`tput setaf 4`
reset=`tput sgr0`

user=`cat /etc/passwd | grep $username`
if [ "$user" != "$NULL" ]; then
	sudo passwd -l $username
	if [ "$(pgrep -u $username)" != "$NULL" ]; then
		sudo kill -9 $(pgrep -u $username)
	fi
	sudo userdel -r $username
	echo "${found}THE USER HAS BEEN DELETED!!"
else
	echo "${not_found}SELECTED USER DOES NOT EXIST"
fi
